# Generated by Django 2.0.6 on 2018-06-18 20:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Activite',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Cotisation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reglement', models.BooleanField(verbose_name='réglement reçu')),
            ],
        ),
        migrations.CreateModel(
            name='Membre',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prenom', models.CharField(max_length=200)),
                ('nom', models.CharField(max_length=200)),
                ('adresse', models.CharField(max_length=200)),
                ('code_postal', models.CharField(max_length=5, verbose_name='code postal')),
                ('localite', models.CharField(max_length=100, verbose_name='localité')),
                ('tel', models.CharField(max_length=14, verbose_name='téléphone')),
                ('naissance', models.DateField(verbose_name='date de naissance')),
                ('email', models.CharField(max_length=200)),
                ('date_certificat', models.DateField(verbose_name='date de certificat médical')),
                ('remarque', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Tarif',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=200)),
                ('annee', models.IntegerField(verbose_name='année')),
                ('montant', models.IntegerField(verbose_name='montant')),
                ('activite', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adm.Activite', verbose_name='activité')),
            ],
        ),
        migrations.AddField(
            model_name='membre',
            name='activites',
            field=models.ManyToManyField(through='adm.Cotisation', to='adm.Tarif'),
        ),
        migrations.AddField(
            model_name='cotisation',
            name='membre',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adm.Membre'),
        ),
        migrations.AddField(
            model_name='cotisation',
            name='tarif',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adm.Tarif'),
        ),
    ]
