# Generated by Django 2.0.6 on 2018-06-18 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adm', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='membre',
            options={'ordering': ['-nom', '-prenom']},
        ),
        migrations.AlterField(
            model_name='membre',
            name='date_certificat',
            field=models.DateField(blank=True, null=True, verbose_name='date de certificat médical'),
        ),
        migrations.AlterField(
            model_name='membre',
            name='email',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='membre',
            name='remarque',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
